name: Daily Chart Email Sender

on:
  schedule:
    - cron: '0 14 * * *'  # প্রতি দিন দুপুর ৮টা (বাংলাদেশ টাইম: UTC+6 → UTC 14)
  workflow_dispatch:       # ম্যানুয়ালি রান করার অপশন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the chart email script
        run: node index.js
        env:
          EMAIL_USER: shohoj@bijoy2.shop
          EMAIL_PASS: tzUTO3JFH0G1SEgp
          MONGO_URI: mongodb+srv://cftracker:092406030124@cluster0.f7vok.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
